config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => { :registrations => "registrations" }

  root 'home#index'
  resources :pages, only: [:show]
  resources :cards, only: [:show, :update]
  resources :points, only: [:create, :update]

  get '/search', to: 'search#index'

  namespace :admin do
    resources :categories
    put '/reorder', to: 'categories#reorder'

    resources :content

    resources :pages do
      put '/reorder', to: 'pages#reorder'
    end
    resources :graphs do
      resources :lines, only: [:update]
      resources :points, only: [:update, :create, :destroy]
    end
    resources :external_graphs, only: [:index, :create, :update, :show, :destroy]
    resources :cards
    get '/manage_admins/', to: 'manage_admins#index'
    put '/manage_admins/:id', to: 'manage_admins#update'
    post '/manage_admins', to: 'manage_admins#create'
    delete '/manage_admins/:id', to: 'manage_admins#destroy'
  end
end

app/views/admin/pages/_manage_cards.html.erb
<div class="row section-holder">
  <div class="col-md-12">
    <h4>Cards (click to edit)</h4>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Order</th>
          <th>Title</th>
          <th>Page</th>
          <th>Updated By</th>
          <th>Updated At</th>
          <th>Manage</th>
          <th>Destroy</th>
        </tr>
      </thead>
      <tbody>
        <% @page.cards.each do |card| %>
          <tr>
            <td><%= best_in_place(card, :order, url: admin_card_path(card)) %></td>
            <td><%= best_in_place(card, :title, url: admin_card_path(card)) %></td>
            <td><%= best_in_place(card, :page_id, type: :select, collection:  Page.options_for_best_in_place, url: admin_card_path(card)) %></td>
            <td> <%= card.admin.email %></td>
            <td> <%= card.updated_at %></td>
            <td><%= link_to('Manage', admin_card_path(card)) %></td>
            <% if current_admin.super_admin %>
              <td><%= link_to('Destroy', admin_card_path(card), method: :delete, data: { confirm: 'Are you certain you want to delete this card?' }) %></td>
            <% else %>
              <td>Only Super Admins</td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row section-holder">
  <div class="col-md-6 col-md-offset-3">
    <h2 class="text-center">Add Cards</h2>
    <p class="text-center">Create colorful cards for the dashboard.</p>
    <%= form_for(Card.new, url: admin_cards_path) do |f| %>
      <div class="form-group">
        <%= f.hidden_field(:page_id, value: @page.id) %>
      </div>
      <div class="form-group">
        <%= f.label('Order', class: 'padded-label') %>
        <%= f.number_field :order, autofocus: true, placeholder: 'Order (1)', class: 'form-control', required: true %>
      </div>
      <div class="form-group">
        <%= f.label('Title', class: 'padded-label') %>
        <%= f.text_field :title, autofocus: true, placeholder: 'Title for graph', class: 'form-control', required: true %>
      </div>
      <div class="form-group">
        <%= f.submit 'Update Card', class: 'btn btn-success btn-wide', id: 'submit_button', required: true %>
      </div>
    <% end%>
  </div>
</div>

app/views/admin/pages/_manage_graphs.html.erb
<div class="row section-holder">
  <div class="col-md-12">
    <h4>Graphs (click to edit)</h4>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Order</th>
          <th>Title</th>
          <th>Width</th>
          <th>Unit</th>
          <th>Url</th>
          <th>Page</th>
          <th>Updated By</th>
          <th>Updated at</th>
          <th>Manage</th>
          <th>Destroy</th>
        </tr>
      </thead>
      <tbody>
        <% @page.contents.each do |graph| %>
          <% if graph.class == Graph %>
            <tr>
              <td><%= best_in_place(graph, :order, url: admin_graph_path(graph)) %></td>
              <td><%= best_in_place(graph, :title, url: admin_graph_path(graph)) %></td>
              <td><%= best_in_place(graph, :width, type: :select, collection:  { '12': 'Full', '6': 'Half', '4': 'Third', '3': 'Quarter' }, url: admin_graph_path(graph)) %></td>
              <td><%= best_in_place(graph, :unit, url: admin_graph_path(graph)) %></td>
              <td></td>
              <td><%= best_in_place(graph, :page_id, type: :select, collection:  Page.options_for_best_in_place, url: admin_graph_path(graph)) %></td>
              <td><%= graph.created_by %></td>
              <td><%= graph.updated_at %></td>
              <td><%= link_to('Manage', admin_graph_path(graph)) %></td>
              <% if current_admin.super_admin %>
                <td><%= link_to('Destroy', admin_graph_path(graph), method: :delete, data: { confirm: 'Are you certain you want to delete this page?' }) %></td>
              <% else %>
                <td>Only Super Admins</td>
              <% end %>
            </tr>
          <% else %>
            <tr>
              <td><%= best_in_place(graph, :order, url: admin_external_graph_path(graph)) %></td>
              <td><%= best_in_place(graph, :title, url: admin_external_graph_path(graph)) %></td>
              <td><%= best_in_place(graph, :width, type: :select, collection:  { '12': 'Full', '6': 'Half', '4': 'Third', '3': 'Quarter' }, url: admin_external_graph_path(graph)) %></td>
              <td></td>
              <td><%= best_in_place(graph, :external_url, url: admin_external_graph_path(graph)) %></td>
              <td><%= best_in_place(graph, :page_id, type: :select, collection:  Page.options_for_best_in_place, url: admin_external_graph_path(graph)) %></td>
              <td><%= graph.created_by %></td>
              <td><%= graph.updated_at %></td>
              <td><%= link_to('Manage', admin_external_graph_path(graph)) %></td>
              <% if current_admin.super_admin %>
                <td><%= link_to('Destroy', admin_external_graph_path(graph), method: :delete, data: { confirm: 'Are you certain you want to delete this page?' }) %></td>
              <% else %>
                <td>Only Super Admins</td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<div class="row section-holder">
  <h1 class="text-center">Add graphs and content to the page.</h1>
  <div class="col-md-6">
    <h2 class="text-center">Internal</h2>
    <p class="text-center">This data is stored in the app and renders a chart on the website.  No external calls are make to display the data</p>
    <%= form_for(Graph.new, url: admin_graphs_path) do |f| %>
      <div class="form-group">
        <%= f.hidden_field(:page_id, value: @page.id) %>
      </div>
      <div class="form-group">
        <%= f.label('Order', class: 'padded-label') %>
        <%= f.number_field :order, autofocus: true, placeholder: 'Order (1)', class: 'form-control', required: true %>
      </div>
      <div class="form-group">
        <%= f.label('Title', class: 'padded-label') %>
        <%= f.text_field :title, autofocus: true, placeholder: 'Title for graph', class: 'form-control', required: true %>
      </div>
      <div class="form-group">
        <%= f.label('Units', class: 'padded-label') %>
        <%= f.text_field :unit, autofocus: true, placeholder: 'Calls per day', class: 'form-control', required: true %>
      </div>
      <div class="form-group">
        <%= f.submit 'Create Internal Graph', class: 'btn btn-success btn-wide', id: 'submit_button', required: true %>
      </div>
    <% end%>
  </div>

  <div class="col-md-6">
    <h2 class="text-center">External</h2>
    <p class="text-center">Sometimes data is stored and charted in a different program ie Tableau or MapBox.  Paste a link to the graphic you want to include below.</p>
    <%= form_for(ExternalGraph.new, url: admin_external_graphs_path) do |f| %>
      <div class="form-group">
        <%= f.hidden_field(:page_id, value: @page.id) %>
      </div>
      <div class="form-group">
        <%= f.label('Order', class: 'padded-label') %>
        <%= f.number_field :order, autofocus: true, placeholder: 'Order (1)', class: 'form-control', required: true %>
      </div>
      <div class="form-group">
        <%= f.label('Title', class: 'padded-label') %>
        <%= f.text_field :title, autofocus: true, placeholder: 'Title for graph', class: 'form-control', required: true %>
      </div>
      <div class="form-group">
        <%= f.label('Url', class: 'padded-label') %>
        <%= f.text_field :external_url, autofocus: true, placeholder: 'https://www.link_to_chart.com', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit 'Create External Graph', class: 'btn btn-success btn-wide', id: 'submit_button' %>
      </div>
    <% end%>
  </div>
</div>

app/views/admin/pages/_panel_row.html.erb
<li id="page-listitem-<%= page.id %>" data-id=<%= page.id %>>
  <div class="page-listitem sort-container">
    &nbsp<i class="fa fa-sort" aria-hidden="true"></i>
  </div>
  <div class="page-listitem name-container">
    <%= best_in_place page, :name, url: admin_page_url(page) %>
  </div>
  <div class="page-listitem actions-container">
    <%= link_to admin_page_url(page), class: 'text-right' do%>
      <i class="fa fa-pencil" aria-hidden="true"></i>
    <% end %>
    &nbsp
    <%= link_to admin_page_url(page), data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'text-right' do %>
      <i class="fa fa-trash" aria-hidden="true"></i>
    <% end %>
  </div>
</li>

app/views/admin/pages/create.js.erb
var list = $("#category-page-list-<%= @page.category.id %>")
var html = "<%= j render '/admin/pages/panel_row', page: @page %>"

list.append(html);
jQuery(".best_in_place").best_in_place();

app/views/admin/pages/index.html.erb
<% provide :title, 'Pages' %>

<h1 class="text-center">Pages without a category</h1>

<div class="row section-holder">
</div>

<script>
  $(document).ready(function() {
    $("#page_category_id").select2({});
    jQuery(".best_in_place").best_in_place();
  });
</script>

app/views/admin/pages/show.html.erb
<% provide :title, @page.name %>

<h1 class="text-center"><%= "Manage #{@page.name}" %></h1>
</br>

<div class="section-holder row">
  <h2 class="text-center">Introduction Text <small>click to edit</small></h2>
  <div class="col-md-10 col-md-offset-1">
    <h4>
      <%= best_in_place @page, :intro_text, url: admin_page_url(@page), as: :textarea %>
    </h4>
  </div>
</div>


<div class="section-holder row">
  <div class="col-md-6 col-md-offset-3">
    <h3>
      Add Content
    </h3>
    <input type="text" class="form-control" autocomplete="off" placeholder="Search Content" name="query" id="content-search-input">
  </div>
</div>

<div class="section-holder">
  <table class="table table-striped table-bordered" id="content-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Type</th>
        <th>Manage</th>
        <th>Remove</th>
      </tr>
    </thead>
    <tbody>
      <% @page.contents.each do |content| %>
        <%= render '/admin/content/page_row', content: content %>
      <% end %>
    </tbody>
  </table>
</div>

<script>
  jQuery(".best_in_place").best_in_place();
  var fixHelper = function(e, ui) {
    ui.children().each(function() {
      $(this).width($(this).width());
    });
    return ui
  };
  $("#content-table tbody").sortable({
    helper: fixHelper,
    revert: 'invalid',
    placeholder: 'placeholder',
    forceHelperSize: true,
    start: function( event, ui ) {
      ui.placeholder.height(ui.item.height())
      ui.placeholder.width(ui.item.width())
    },
    update: function(event, ui) {
      var contentIds = $.map($(event.target).children('tr'), function(n) { return $(n).data('id')});
      $.ajax({
        data: { content_ids: contentIds },
        url: "<%= admin_page_reorder_url(@page) %>",
        type: 'PUT',
        success: function(response) {
        }
      });
    }
  }).disableSelection();

  $("#content-search-input").autocomplete({
    minLength: 3,
    source: function (request, response) {
      jQuery.get("/search", { query: request.term },
        function (data) {
          results = $.map(data, function (user, index) {
            return user;
          });
        response(results);
      });
    },
    focus: function(event, ui) {
      event.preventDefault();
    },
    select: function(event, ui) {
      event.preventDefault();
      $.ajax({
        type: "POST",
        url: '/admin/content',
        data: { content: {
          'page_id': <%= @page.id %>,
          'content_type':ui.item.class,
          'content_id': ui.item.id,
          'order': 0 }
        },
      });
    },
    minLength: 1
    }).data("ui-autocomplete")._renderItem = function(ul, item) {
        var $a = $("<a></a>");
        console.log(item);
        console.log(item.tags);
        var inner_html = '<div class="advanced-search-result-container">' +
            '<div class="advanced-search-result-image-container">' +
            '<i class="fa fa-' + item.icon + '" aria-hidden="true"></i>' +
            '</div>' +
            '<div class="advanced-search-result-text-container">' +
            '<h5>' + item.title  + '</h5>' +
              '<p>' + item.admin + '</p>' +
            '</div>'
          '</div>';
        return $( "<li></li>" )
          .data( "item.autocomplete", item )
          .append(inner_html)
          .appendTo( ul );
      };
</script>