config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => { :registrations => "registrations" }

  root 'home#index'
  resources :pages, only: [:show]
  resources :cards, only: [:show, :update]
  resources :points, only: [:create, :update]

  get '/search', to: 'search#index'

  namespace :admin do
    resources :categories
    put '/reorder', to: 'categories#reorder'

    resources :content

    resources :pages do
      put '/reorder', to: 'pages#reorder'
    end
    resources :graphs do
      resources :lines, only: [:update]
      resources :points, only: [:update, :create, :destroy]
    end
    resources :external_graphs, only: [:index, :create, :update, :show, :destroy]
    resources :cards
    get '/manage_admins/', to: 'manage_admins#index'
    put '/manage_admins/:id', to: 'manage_admins#update'
    post '/manage_admins', to: 'manage_admins#create'
    delete '/manage_admins/:id', to: 'manage_admins#destroy'
  end
end

app/models/graph.rb
class Graph < ActiveRecord::Base
  include PgSearch
  validates :title, uniqueness: true
  validates :width, :inclusion => { :in => [12, 6, 4, 3] }
  validates :style, :inclusion => { :in => ['spline', 'bar'] }
  has_many :lines
  after_create :set_lines
  belongs_to :page
  belongs_to :admin
  has_many :contents
  has_many :pages, through: :contents

  multisearchable :against => [:title, :admin_email]

  def admin_email
    admin.email
  end

  def pages
    Content.where(content_id: id, content_type: 'Graph').map(&:page)
  end

  def to_search_result
    {
      id: id,
      class: 'Graph',
      title: title,
      admin: admin.try(:email),
      icon: 'line-chart'
    }
  end

  def data
    data = []
    lines.each do |line|
      line.points.each do |point|
        data << { 'dateField' => point.time,
                  'line' => line.title,
                  'style' => style,
                  line.title => point.value }
      end
    end
    data
  end

  def line_data
    lines.map do |line|
      {
        'title' => line.title,
        'style' => style,
      }
    end
  end

  def created_by
    admin.email if admin
  end

  private

  def set_lines
    self.lines = [Line.create(title: 'Goal'), Line.create(title: 'Data')]
  end
end

app/controllers/admin/graphs_controller.rb
class Admin::GraphsController < AdminController
  def index
  end

  def create
    @graph = Graph.create(graph_params)
    redirect_to admin_page_path(@graph.page)
  end

  def show
    @graph = Graph.find(params[:id])
  end

  def update
    @graph = Graph.find(params[:id])
    respond_to do |format|
      if @graph.update(graph_params)
        format.json { render json: @graph }
      else
        format.json { render json: @graph.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @graph = Graph.find_by(id: params[:id])
    if current_admin.super_admin
      @graph.destroy
    end
    redirect_to admin_content_index_url
  end

  private

  def graph_params
    ps = params.require(:graph)
          .permit(:order, :title, :unit, :page_id, :width, :style)
    ps[:admin_id] = current_admin.id
    ps
  end
end

app/views/admin/graphs/_form.html.erb
<h2 class="text-center">Internal</h2>
<p class="text-center">This data is stored in the app and renders a chart on the website.  No external calls are make to display the data</p>
<%= form_for(Graph.new, url: '/admin/graphs') do |f| %>
  <div class="form-group">
    <%= f.label('Page', class: 'padded-label') %>
    <%= f.select(:page_id, options_for_select(Page.options_for_select), required: true) %>
  </div>
  <div class="form-group">
    <%= f.label('Order', class: 'padded-label') %>
    <%= f.number_field :order, autofocus: true, placeholder: 'Order (1)', class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label('Title', class: 'padded-label') %>
    <%= f.text_field :title, autofocus: true, placeholder: 'Title for graph', class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label('Units', class: 'padded-label') %>
    <%= f.text_field :unit, autofocus: true, placeholder: 'Calls per day', class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Internal Graph', class: 'btn btn-success btn-wide', id: 'submit_button', required: true %>
  </div>
<% end%>

<script>
    $("#graph_page_id").select2({});
</script>

app/views/admin/graphs/show.html.erb
<div class="row section-holder">
  <h1 class="text-center"><%= "Manage #{@graph.title}" %></h1>
  <%  @graph.pages.each do |page| %>
    <% next unless page %>
    <h3 class="text-center"><%= link_to page.name, admin_page_path(page) %></h3>
  <% end %>
  <h3 class="text-center"><%= "Data for #{@graph.title}" %></h3>

  <div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <%= render '/graphs/graph', graph: @graph %>
      </div>
    </div>
  </div>

  <div class="section-holder">
    <div class="row">
      <div class="col-md-3 col-md-offset-3">
        <h4 class="text-right">Choose Graph Style:</h4>
      </div>
      <div class="col-md-3">
        <h4>
          <%= best_in_place(@graph, :style, type: :select, collection:  { 'spline': 'spline', 'bar': 'bar' }, url: admin_graph_path(@graph), id: 'graph_style_selector') %>
        </h4>
      </div>
    </div>
  </div>


  <% @graph.lines.each do |line| %>
    <div class="section-holder">
      <div class="row">
        <div class= col-md-12>
          <h3 class="text-center"><%= best_in_place(line, :title, url: admin_graph_line_path(@graph, line)) %></h3>
          <table class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Order</th>
                <th>Time</th>
                <th>Value</th>
                <th>Notes</th>
                <th>Updated By</th>
                <th>Updated at</th>
                <th>Destroy</th>
              </tr>
            </thead>
            <tbody>
              <% line.points.each do |point| %>
                <tr>
                  <td><%= best_in_place(point, :position, url: admin_graph_point_path(@graph, point)) %></td>
                  <td><%= best_in_place(point, :time, url: admin_graph_point_path(@graph, point)) %></td>
                  <td><%= best_in_place(point, :value, url: admin_graph_point_path(@graph, point)) %></td>
                  <td><%= best_in_place(point, :notes, as: :textarea, url: admin_graph_point_path(@graph, point)) %></td>
                  <td><%= point.created_by %></td>
                  <td><%= point.updated_at %></td>
                  <% if current_admin.super_admin %>
                    <td><%= link_to('Destroy', admin_graph_point_path(@graph, point), method: :delete, data: { confirm: 'Are you certain you want to delete this point?' }) %></td>
                  <% else %>
                    <td>Only Super Admins</td>
                  <% end %>
                </tr>
              <% end %>
              <tr>
                <%= form_for(Point.new, url: admin_graph_points_path(@graph)) do |f| %>
                  <%= f.hidden_field :line_id, value: line.id %>
                  <td><%= f.text_field :position, placeholder: 'Order', class: 'form-control', id: "#{line.id}-date-field" %></td>
                  <td><%= f.text_field :time, placeholder: 'Time', class: 'form-control', id: "#{line.id}-date-field" %></td>
                  <td><%= f.text_field :value, autofocus: true, placeholder: 'Value', class: 'form-control' %></td>
                  <td><%= f.text_area :notes, autofocus: true, placeholder: 'Notes', class: 'form-control' %></td>
                  <td><%= f.submit 'Create Point', class: 'btn btn-success btn-wide', id: 'submit_button' %></td>
                <% end %>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
  $(document).ready(function() {
    jQuery(".best_in_place").best_in_place();
  });
  $('#graph_style_selector').bind("ajax:success", function(){
    location.reload();
  });
</script>