config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => { :registrations => "registrations" }

  root 'home#index'
  resources :pages, only: [:show]
  resources :cards, only: [:show, :update]
  resources :points, only: [:create, :update]

  get '/search', to: 'search#index'

  namespace :admin do
    resources :categories
    put '/reorder', to: 'categories#reorder'

    resources :content

    resources :pages do
      put '/reorder', to: 'pages#reorder'
    end
    resources :graphs do
      resources :lines, only: [:update]
      resources :points, only: [:update, :create, :destroy]
    end
    resources :external_graphs, only: [:index, :create, :update, :show, :destroy]
    resources :cards
    get '/manage_admins/', to: 'manage_admins#index'
    put '/manage_admins/:id', to: 'manage_admins#update'
    post '/manage_admins', to: 'manage_admins#create'
    delete '/manage_admins/:id', to: 'manage_admins#destroy'
  end
end

app/models/external_graph.rb
class ExternalGraph < ActiveRecord::Base
  include PgSearch
  validates :title, uniqueness: true
  validates :width, :inclusion => { :in => [12, 6, 4, 3] }
  belongs_to :admin
  has_many :contents
  has_many :pages, through: :contents
  has_many :tag_joins, as: :taggable
  has_many :tags, through: :tag_joins

  multisearchable :against => [:title, :admin_email]

  def admin_email
    admin.email if admin
  end

  def pages
    Content.where(content_id: id, content_type: 'ExternalGraph').map(&:page)
  end

  def to_search_result
    {
      id: id,
      class: 'ExternalGraph',
      title: title,
      admin: admin.try(:email),
      icon: 'code'
    }
    end

  def created_by
    admin.email if admin
  end
end

app/controllers/admin/external_graphs_controller.rb
class Admin::ExternalGraphsController < AdminController
  def index
  end

  def create
    @external_graph = ExternalGraph.create(external_graph_params)
    redirect_to admin_external_graph_path(@external_graph)
  end

  def show
    @external_graph = ExternalGraph.find(params[:id])
  end

  def update
    @external_graph = ExternalGraph.find(params[:id])
    respond_to do |format|
      if @external_graph.update(external_graph_params)
        format.html { render :show }
        format.json { render json: @external_graph }
      else
        format.json { render json: @external_graph.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @external_graph = ExternalGraph.find_by(id: params[:id])
    if current_admin.super_admin
      @external_graph.destroy
    end
    redirect_to admin_content_index_url
  end

  private

  def external_graph_params
    ps = params.require(:external_graph)
          .permit(:order, :title, :external_url, :page_id,
                  :width, :height, :tags => [])
    ps[:admin_id] = current_admin.id
    if ps[:tags]
      ps[:tags] = ps[:tags].delete_if { |tag| tag.blank? }
      ps[:tags] = ps[:tags].map { |tag| Tag.where(name: tag).first_or_create }
    end
    ps
  end
end

app/views/admin/external_graphs/_form.html.erb
<h2 class="text-center">External</h2>
<p class="text-center">Sometimes data is stored and charted in a different program ie Tableau or MapBox.  Paste a link to the graphic you want to include below.</p>
<%= form_for(ExternalGraph.new, url: admin_external_graphs_path) do |f| %>
  <div class="form-group">
    <%= f.label('Page', class: 'padded-label') %>
    <%= f.select(:page_id, options_for_select(Page.options_for_select), required: true) %>
  </div>
  <div class="form-group">
    <%= f.label('Order', class: 'padded-label') %>
    <%= f.number_field :order, autofocus: true, placeholder: 'Order (1)', class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label('Title', class: 'padded-label') %>
    <%= f.text_field :title, autofocus: true, placeholder: 'Title for graph', class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label('Url', class: 'padded-label') %>
    <%= f.text_field :external_url, autofocus: true, placeholder: 'https://www.link_to_chart.com', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label('Height', class: 'padded-label') %>
    <%= f.number_field :height, autofocus: true, placeholder: '400', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create External Graph', class: 'btn btn-success btn-wide', id: 'submit_button' %>
  </div>
<% end%>

app/views/admin/external_graphs/show.html.erb
<div class="row section-holder">
  <h1 class="text-center"><%= "Preview of #{@external_graph.title}" %></h1>

    <%  @external_graph.pages.each do |page| %>
      <h3 class="text-center"><%= link_to page.name, admin_page_path(page) %></h3>
    <% end %>

  <div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <%= render '/external_graphs/external_graph', graph: @external_graph %>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Edit</h4>
      <%= form_for(@external_graph, url: admin_external_graph_path(@external_graph)) do |f| %>
        <div class="form-group">
          <%= f.label('Title', class: 'padded-label') %>
          <%= f.text_field :title, autofocus: true, placeholder: 'Title for external graph', class: 'form-control', required: true %>
        </div>
        <div class="row">
          <div class="col-sm-6">
            <div class="form-group">
              <%= f.label(:width, class: 'padded-label') %>
              <%= f.select :width, {'Full' => '12', 'Half' => '6', 'Third' => '4', 'Quarter' => '3'},
                                   {},
                                   class: 'form-control', required: true %>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="form-group">
              <%= f.label(:height, class: 'padded-label') %>
              <%= f.number_field :height, autofocus: true, placeholder: 'height', class: 'form-control', required: true %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <%= f.label(:external_url, class: 'padded-label') %>
          <%= f.text_field :external_url, placeholder: 'http://website.com', autofocus: true, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label('Tags', class: 'padded-label') %>
          <%= f.select(:tags, options_for_select(Tag.pluck(:name), @external_graph.tags.pluck(:name)),
                              {},
                              { multiple: true , required: true }) %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update External Graph', class: 'btn btn-success btn-wide', id: 'submit_button', required: true %>
        </div>
      <% end%>
    </div>
  </div>
</div>
<script>
  $(document).ready(function() {
    jQuery(".best_in_place").best_in_place();
  });
 $("#external_graph_width").select2({ });
 $("#external_graph_tags").select2({
   tags: true,
   multiple: true,
 });
</script>