config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => { :registrations => "registrations" }

  root 'home#index'
  resources :pages, only: [:show]
  resources :cards, only: [:show, :update]
  resources :points, only: [:create, :update]

  get '/search', to: 'search#index'

  namespace :admin do
    resources :categories
    put '/reorder', to: 'categories#reorder'

    resources :content

    resources :pages do
      put '/reorder', to: 'pages#reorder'
    end
    resources :graphs do
      resources :lines, only: [:update]
      resources :points, only: [:update, :create, :destroy]
    end
    resources :external_graphs, only: [:index, :create, :update, :show, :destroy]
    resources :cards
    get '/manage_admins/', to: 'manage_admins#index'
    put '/manage_admins/:id', to: 'manage_admins#update'
    post '/manage_admins', to: 'manage_admins#create'
    delete '/manage_admins/:id', to: 'manage_admins#destroy'
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :admin
  has_many :pages
  default_scope { order(:order) }

  def created_by
    admin.email if admin
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  def index
    @categories = Category.all
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    respond_to do |format|
      format.js
      format.html { redirect_to admin_categories_path }
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    respond_to do |format|
      if update_category
        format.json { render json: @category }
      else
         format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if current_admin.super_admin
      Category.find_by(id: params[:id]).destroy
    end
    redirect_to admin_categories_path
  end

  def reorder
    params[:category_ids].each_with_index do |category_id, index|
      Category.where(id: category_id).update_all(order: index)
    end
    respond_to do |format|
      format.json { render json: true }
    end
  end

  private

  def category_params
    ps = params.require(:category).permit(:name, :order, :pages => [])
    ps[:pages] = ps[:pages].map { |page_id| Page.find(page_id) } if ps[:pages]
    ps[:admin_id] = current_admin.id
    ps
  end

  def update_category
    @category.update(category_params)
    update_pages if category_params[:pages]
    true
  end

  def update_pages
    @category.pages.update_all(category_id: 0, order: -1)
    category_params[:pages].each_with_index do |page, i|
      page.update(order: i, category_id: @category.id)
    end

    @category.pages.where(order: -1).update_all(category_id: 0)
  end
end

app/views/admin/categories/_panel.html.erb
<li class="panel panel-info" data-url="<%= admin_reorder_url %>" data-id="<%= category.id %>" >
  <div class="panel-heading">
    &nbsp<i class="fa fa-sort" aria-hidden="true"></i>&nbsp
    <%= best_in_place category, :name, url: admin_category_url(category) %> &nbsp
    <%= link_to admin_category_url(category), data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'text-right' do %>
      <i class="fa fa-trash" aria-hidden="true"></i>
    <% end %>
  </div>
  <div class="panel-body">
    <ul class="category-page-list sortable-page" id="category-page-list-<%= category.id %>" data-url="<%= admin_category_url(category) %>" data-id="<%= category.id%>">
      <% category.pages.each do |page| %>
        <%= render '/admin/pages/panel_row', page: page %>
      <% end %>
    </ul>
  </div>
</li>

app/views/admin/categories/create.js.erb
var list = $(".sortable-category")
var html = "<%= j render '/admin/categories/panel', category: @category %>"

list.append(html);
jQuery(".best_in_place").best_in_place();

$(".sortable-page").sortable({
  connectWith: ".sortable-page",
  update: function(event, ui) {
    var params = {};
    params['pages'] = $.map($(event.target).children('li'), function(n) { return $(n).data('id')});
    var categoryUrl = $(event.target).data('url');
    $.ajax({
      data: { category: params },
      url: categoryUrl,
      type: 'PUT',
      success: function(response) {
      }
    });
  }
});

app/views/admin/categories/index.html.erb
<% provide :title, 'Categories' %>

<h1 class="text-center">Manage Categories</h1>

<div class="row">
    <div class="col-md-3 col-md-offset-3">
      <%= form_for Category.new, url: admin_categories_url(format: :js), remote: true, authenticity_token: true do |f| %>
        <%= f.hidden_field :admin_id, value: current_admin.id %>
        <%= f.hidden_field :name, value: "New Category" %>
        <%= f.submit 'Create Category', class: 'btn btn-primary btn-wide' %>
      <% end %>
    </div>
    <div class="col-md-3">
      <%= form_for Page.new, url: admin_pages_url(format: :js), remote: true, authenticity_token: true do |f| %>
        <%= f.submit 'Create Page', class: 'btn btn-info btn-wide' %>
        <%= f.hidden_field :admin_id, value: current_admin.id %>
        <%= f.hidden_field :category_id, value: @categories.first.id %>
        <%= f.hidden_field :name, value: "New Page" %>
      <% end %>
    </div>
</div>

</br>

<ul class="section-holder sortable-category">
  <% @categories.each do |category| %>
    <%= render '/admin/categories/panel', category: category %>
  <% end %>
</ul>

<script>
  $(document).ready(function() {
    jQuery(".best_in_place").best_in_place();
    $(".sortable-page").sortable({
      connectWith: ".sortable-page",
      update: function(event, ui) {
        var params = {};
        params['pages'] = $.map($(event.target).children('li'), function(n) { return $(n).data('id')});
        var categoryUrl = $(event.target).data('url');
        $.ajax({
          data: { category: params },
          url: categoryUrl,
          type: 'PUT',
          success: function(response) {
          }
        });
      }
    });

    $(".sortable-category").sortable({
      revert: 'invalid',
      placeholder: 'placeholder',
      forceHelperSize: true,
      start: function( event, ui ) {
        ui.placeholder.height(ui.item.height())
        ui.placeholder.width(ui.item.width())
      },
      update: function(event, ui) {
        var categoryIds = $.map($(event.target).children('li'), function(n) { return $(n).data('id')});
        var categoryUrl = $(event.target).data('url');
        $.ajax({
          data: { category_ids: categoryIds },
          url: '/admin/reorder',
          type: 'PUT',
          success: function(response) {
          }
        });
      }
    });
  });
</script>